apiVersion: v2
appVersion: "2.7.2a"
description: >
  Helm chart to deploy Open5gs UPF service on Kubernetes.
home: https://github.com/sgrannec/5g-charts
sources:
  - http://open5gs.org
icon: https://open5gs.org/assets/img/open5gs-logo.png
maintainers:
- email: stephane.grannec@orange.com
  name: sgrannec
name: open5gs-upf
version: 2.2.6
annotations:
  artifacthub.io/category: networking
keywords:
  - network
  - ngc
  - gradiant
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
